### ISSUE TITLE
Types change: Payload(s) [POST/GET]: `signers` (null | string[])

### ISSUE THREAD

**Issue by WietseWind** [CASL-AE/xumm-sdk-py#29]
## TL;DR:
Payloads have a new `meta` property: `signers`. The field can be `null` or an array containing between one and an arbitrary amount (currently hard capped by our backend at four, client doesn't have to enforce) XRPL account addresses.

When one or more account addresses are entered, XUMM forces signing with one of those accounts.

## Impact:
- [x] Payload GET __types__ (`meta.signers`) (null or string[])
- [x] Paylost POST __types__ (`options.signers`) (omit, null or string[])

## Commit to XUMM-SDK:
https://github.com/XRPL-Labs/XUMM-SDK/commit/8b5c484b23f774de70bcd3c6d95e87dd99d968b4

## Based on discussion:
https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/384#issuecomment-1075098922

**Comment by dangell7** [comment]
GET: https://github.com/XRPL-Labs/xumm-sdk-py/commit/cc4e5b7239fc45dbce1af667edcf1e5a42002e6b
POST: https://github.com/XRPL-Labs/xumm-sdk-py/commit/dbe040f409ffc5f918086a12f190ef289e709d22

**Comment by WietseWind** [comment]
Thank you!
